/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.usermanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author gk005
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    private int otp;
    User user;
    
    public Login() {
        initComponents();
        reloadLoginGUI();
    }

    private void reloadLoginGUI(){
        lblTitle.setText("Login");
        lblUserIDOrEmail.setText("User ID");
        lblPassword.setVisible(true);
        txtInputPassword.setVisible(true);
        btnLogin.setText("Login");
        lblForgotPassword.setText("※Forgot Password");
    }
    
    private void reloadForgotPasswordGUI(){
        lblTitle.setText("Password Reset");
        lblUserIDOrEmail.setText("Email");
        txtInputUserIDOrEmail.setText("");
        lblPassword.setVisible(false);
        txtInputPassword.setVisible(false);
        btnLogin.setText("Send OTP");
        lblForgotPassword.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtInputPassword = new javax.swing.JPasswordField();
        txtInputUserIDOrEmail = new javax.swing.JTextField();
        lblUserIDOrEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblRed = new javax.swing.JLabel();
        lblForgotPassword = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInputUserIDOrEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputUserIDOrEmailActionPerformed(evt);
            }
        });

        lblUserIDOrEmail.setText("User ID");

        lblPassword.setText("Password");

        lblTitle.setText("Login");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblRed.setForeground(new java.awt.Color(255, 0, 0));

        lblForgotPassword.setForeground(new java.awt.Color(0, 153, 255));
        lblForgotPassword.setText("※Forgot Password");
        lblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblForgotPassword)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblUserIDOrEmail)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtInputPassword)
                                .addComponent(txtInputUserIDOrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRed))
                        .addContainerGap(104, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUserIDOrEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInputUserIDOrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addGap(10, 10, 10)
                .addComponent(txtInputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForgotPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRed)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtInputUserIDOrEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputUserIDOrEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputUserIDOrEmailActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String btnText = btnLogin.getText();
        if (btnText.equals("Login")) {
            String enteredID = txtInputUserIDOrEmail.getText();
            lblRed.setVisible(false);
            String enteredPassword = new String(txtInputPassword.getPassword());
            
            if (enteredID.isEmpty() || enteredPassword.isEmpty()) {
                lblRed.setVisible(true);
                lblRed.setText("※ID and Password are required.");
                return;
            }
            
            UserFileReader reader = new UserFileReader("student_information.csv");
            LoginManager logiManager = new LoginManager(reader);
            
            User user = logiManager.login(enteredID, enteredPassword);
             
            if(user == null){
                lblRed.setVisible(true);
                lblRed.setText("※ID or Password is incorect.");
                txtInputPassword.setText("");
                return;
            }
        
            SessionManager.setLoggedUser(user);
        
            Menu menu = new Menu();
            menu.setVisible(true);
            this.dispose();
        
        }else if(btnText.equals("Send OTP")){
            String InputEmail = txtInputUserIDOrEmail.getText();
            
            UserFileReader reader = new UserFileReader("student_information.csv");
            user = reader.findUserByEmail(InputEmail);
            
            if (user == null) {
                JOptionPane.showMessageDialog(null, "Email not found.");
            }else{
                gmailservice gmail = new gmailservice();
                boolean success = gmail.sendOTPEmail(InputEmail);
                
                if (!success) {
                    JOptionPane.showMessageDialog(this, "Failed to send Email.");
                    return;
                }else{
                    JOptionPane.showMessageDialog(this, "Check your email.");
                    otp = gmail.getCurrentOtp();
                    lblUserIDOrEmail.setText("One Time Password");
                    txtInputUserIDOrEmail.setText("");
                    btnLogin.setText("OK");
                }
            }  
        }else{
            String inputOTP = txtInputUserIDOrEmail.getText();
            if (inputOTP.equals(String.valueOf(otp))) {
                SessionManager.setLoggedUser(user);
                
                PasswordReset resetGUI = new PasswordReset(true);
                resetGUI.setVisible(true);
                
                this.dispose();
            }else{
                txtInputUserIDOrEmail.setText("");
                lblRed.setText("The OTP is incorrect.");
            }
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseClicked
        // TODO add your handling code here:
        reloadForgotPasswordGUI();      
    }//GEN-LAST:event_lblForgotPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserIDOrEmail;
    private javax.swing.JPasswordField txtInputPassword;
    private javax.swing.JTextField txtInputUserIDOrEmail;
    // End of variables declaration//GEN-END:variables
}
