/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.usermanagement;

/**
 *
 * @author gk005
 */
public class MainMenuStudent extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuStudent.class.getName());
    
    private Student loggedStudent;
    private User loggedUser;
    /**
     * Creates new form MainMenuStudent
     */
    public MainMenuStudent() {
        initComponents();
    }
    
    public MainMenuStudent(User user){
        this.loggedUser = user;
        initComponents();
        isDisplayable();
        displayUserData();
    }
    
    private void displayUserData(){
        if(loggedUser != null){
            lblsUserName.setText("User Name: " + loggedUser.getFirstName() + " " + loggedUser.getLastName());
            lblsUserID.setText("Student ID: " + loggedUser.getUserID());
            lblsEmail.setText("Email: " + loggedUser.getEmail());
            
            if(loggedUser instanceof Student student){
                lblsMajor.setVisible(true);
                lblsMajor.setText("Major: " + student.getMajor() + "(" + student.getYear()+")");
            }else{
                lblsMajor.setVisible(false);
            }
        }
    }
    
        private void configureByRole() {
        switch (loggedUser.getRole()) {
            case "Student":
                //setVisible
                break;
            case "Officer":

                break;
            case "Admin":
                
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblsUserName = new javax.swing.JLabel();
        lblsUserID = new javax.swing.JLabel();
        lblsEmail = new javax.swing.JLabel();
        lblsMajor = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Main Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsEmail)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblsUserName)
                                .addComponent(lblsUserID))
                            .addComponent(lblsMajor))))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsUserName)
                .addGap(18, 18, 18)
                .addComponent(lblsUserID)
                .addGap(18, 18, 18)
                .addComponent(lblsEmail)
                .addGap(40, 40, 40)
                .addComponent(lblsMajor)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Main Menu (Student)");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenuStudent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblsEmail;
    private javax.swing.JLabel lblsMajor;
    private javax.swing.JLabel lblsUserID;
    private javax.swing.JLabel lblsUserName;
    // End of variables declaration//GEN-END:variables
}
