/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.usermanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author gk005
 */
public class PasswordReset extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PasswordReset.class.getName());
    private User loggedUser;
    private String email;
    private boolean isEmailSent;

    public PasswordReset(boolean emailVerified) {
        initComponents();
        this.loggedUser = SessionManager.getLoggedUser();
        this.email = loggedUser.getEmail();
        this.isEmailSent = emailVerified;
        
        pf1.setVisible(false);
        lblPassword2.setVisible(false);
        pf2.setVisible(false);
        lblRed.setVisible(false);
        
        if (!emailVerified) {
            lbltop.setText("Send confirmation email to " + email + "?");
            btnEnter.setText("Send");
            btnBack.setVisible(true);
        }else{
            lbltop.setText("New Password"); 
            pf1.setVisible(true);
            pf2.setVisible(true);
            btnEnter.setText("Change Password");
            btnBack.setVisible(false);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbltop = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        lblPassword2 = new javax.swing.JLabel();
        lblRed = new javax.swing.JLabel();
        pf2 = new javax.swing.JPasswordField();
        pf1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBack.setText("⇦");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Password Reset");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbltop.setText("jLabel1");

        btnEnter.setText("jButton2");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        lblPassword2.setText("jLabel1");

        lblRed.setBackground(new java.awt.Color(255, 0, 0));
        lblRed.setFont(new java.awt.Font("Yu Gothic UI", 0, 8)); // NOI18N
        lblRed.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltop)
                    .addComponent(lblPassword2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pf2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(btnEnter)
                            .addComponent(lblRed, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf1))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblRed)
                .addGap(10, 10, 10)
                .addComponent(btnEnter)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new UserInfo().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        if(isEmailSent==false){ //API
            gmailservice gmail = new gmailservice();
            boolean success = gmail.sendOTPEmail(email);
            
            if(!success){
                JOptionPane.showMessageDialog(this, "Failed to send OTP email. Please try again.");
                return;
            }
            
            String inputOtpStr = JOptionPane.showInputDialog(
                    this,
                    "An OTP has been sent to your email.\nPlease enter it below:",
                    "OTP Verification",
                    JOptionPane.QUESTION_MESSAGE
            );
            
            if(inputOtpStr == null){
                return;
            }
            
            try{
                int inputOtp = Integer.parseInt(inputOtpStr);
                int otp = gmail.getCurrentOtp();
                if(inputOtp == otp){
                    JOptionPane.showMessageDialog(this, "OTP verified! You can now reset your password.");
                    lbltop.setText("New Password");
                    pf1.setVisible(true);
                    lblPassword2.setVisible(true);
                    lblPassword2.setText("Confirm Password");
                    pf2.setVisible(true);
                    btnEnter.setText("Change Password");
                    isEmailSent = true;
                    isEmailSent = true;
                }else{
                    JOptionPane.showMessageDialog(this, "Incorrect OTP. Please try again.");
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Invalid OTP format. Please enter numbers only.");
            }
            
        }else{
            String pass1 = new String(pf1.getPassword());
            String pass2 = new String(pf2.getPassword());
            
            if (pass1 == null || pass1.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter The New Password");
            }else if(pass1.equals(pass2)){                
                User logged = SessionManager.getLoggedUser();
                String oldPass = logged.getPassword();
                logged.setPassword(pass1);
                
                UserFileWriter writer = new UserFileWriter("account_information.csv");
                
                boolean result = writer.updateUserByID(logged.getUserID(),logged);
                
                if(result){
                    JOptionPane.showMessageDialog(
                        null,
                        "Your password has been successflly updated.",
                        "Update Successful",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    
                    this.dispose();
                    new UserInfo().setVisible(true);
                    
                }else{
                    logged.setPassword(oldPass);
                    
                    JOptionPane.showMessageDialog(
                        null,
                        "Failed to update your password.\nPlease try again later",
                        "Update Failed",
                        JOptionPane.ERROR_MESSAGE
                    );
                    
                }
            }else{
                pf2.setText("");
                lblRed.setText("The passwords you entered do not match. Please try again.");
            }
            
            
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lbltop;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JPasswordField pf2;
    // End of variables declaration//GEN-END:variables
}
